<%--
Renders a product entry in a row of product listings.

Required Parameters:
	product
	Product repository item to display
	categoryNav
	Determines if breadcrumbs are updated to reflect category navigation on click through
Optional Parameters:
	displaySiteIndicator
	Indicates whether or not to display a site indicator for cross site products
	mode
	Indicates whether to display the "icon" or "name" site indicators
	searchClickId
	Search click ID parameter appended to the URL to notify reporting service. This parameter
	tells reporting service which search query returned the product. It is usually appended to
	product URLs on search results page.
--%>
<%@ page isELIgnored="false"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<%-- DSP --%>
<%@ taglib prefix="dsp" uri="dsp" %>

<%-- Endeca Taglib --%>
<%@ taglib prefix="endeca" uri="/endeca-infront-assembler/utilityTags" %>

<dsp:page>

	<%-- imports --%>
	<dsp:importbean bean="/atg/dynamo/droplet/Compare"/>
	<dsp:importbean bean="/atg/dynamo/servlet/RequestLocale" var="requestLocale"/>
	<dsp:importbean bean="/atg/repository/seo/BrowserTyperDroplet"/>
	<dsp:importbean bean="/ltd/droplets/SkusFromCurrentBookDroplet" />

	<%-- page parameters --%>
	<dsp:getvalueof var="displaySiteIndicator" param="displaySiteIndicator"/>
	<dsp:getvalueof var="productId" vartype="java.lang.String" param="product.repositoryId"/>
	<dsp:getvalueof var="categoryNav" param="categoryNav"/>
	<dsp:getvalueof var="mode" param="mode"/>
	<dsp:getvalueof var="relProdlabel" param="label"/>

	<dsp:getvalueof var="item" param="product"/>
	<dsp:getvalueof var="bookId" param="bookId"/>
	<dsp:getvalueof var="productTemplateUrl" param="product.template.url"/>
	<c:if test="${not empty productTemplateUrl}">

        <c:if test="${ not empty bookId }">
            <%-- fix for QC-930 --%>
			<dsp:droplet name="/atg/commerce/catalog/BookLookup">
				<dsp:param name="id" param="bookId" />
				<dsp:param name="elementName" value="book"/>
				<dsp:oparam name="output">
					<dsp:getvalueof var="showSoldOut" param="book.showSoldOut" />
				</dsp:oparam>
			</dsp:droplet>
		</c:if>
		<%-- Product Template is set --%>
		<dsp:getvalueof var="pageurl" vartype="java.lang.String" param="product.template.url"/>

		<%--
			CatalogItemLink is used to generate a URL string for a repository
			item. Here we generate the link to the product item passed into
			the droplet.

			Input Parameters:
			item - The repository item or the ID of the repository item to generate the URL for

			Open Parameters:
			output - Serviced when no errors occur

			Output Parameters:
			url - The URL generated by the droplet
		---%>
		<dsp:droplet name="/atg/repository/seo/CatalogItemParentCategoriesURLLookup">
			<dsp:param name="product" param="product" />
			<dsp:oparam name="output">
				<dsp:getvalueof var="parentCategoriesPath" param="parentCategories" />
			</dsp:oparam>
		</dsp:droplet>
		<dsp:droplet name="/atg/repository/seo/CatalogItemLink">
			<dsp:param name="parentCategories" value="${parentCategoriesPath}" />
			<dsp:getvalueof var="dimVal" param="N"/>
			<dsp:param name="dimVal" value="${dimVal}" />	
			<c:if test="${(empty dimVal) && ((not empty categoryId )|| (not empty bookId)) }">
			<dsp:param name="repositoryId" value="${categoryId}"/>
				<dsp:droplet name="/atg/commerce/endeca/cache/DimensionValueCacheDroplet">				
					<c:choose>
						<c:when test="${empty bookId}">
							<dsp:param name="repositoryId" value="${categoryId}"/>
						</c:when>
						<c:otherwise>
							<dsp:param name="repositoryId" value="${bookId}"/>
							<dsp:param name="dimensionName" value="product.book"/>
						</c:otherwise>
					</c:choose>
					<dsp:oparam name="output">
						<dsp:getvalueof var="categoryCacheEntry1" param="dimensionValueCacheEntry" />
					</dsp:oparam>
				</dsp:droplet>
				<%-- Bit of a hack, extracting N value from SEO url as numeral N value wont work if SEO is turned on --%>
				<c:set var="seoURL" value="${categoryCacheEntry1.url}" />			
				<c:set var="seoDimVal" value="${fn:substringAfter(seoURL, '/N-')}" />
				<dsp:param name="dimVal" value="${seoDimVal}" />		
			</c:if>
			
			<dsp:param name="item" param="product"/>						
			<dsp:oparam name="output">

				<%-- generate product link --%>
				
				<c:choose>
				    <c:when test="${ !empty bookId }">
					  <dsp:getvalueof id="tempUrl" idtype="String" param="url"/>
					  <dsp:getvalueof id="finalUrl" idtype="String" value="${tempUrl}?bookId=${bookId}"/>
					</c:when>
					<c:otherwise>
					  <dsp:getvalueof id="finalUrl" idtype="String" param="url" />
					</c:otherwise>
				</c:choose>

				<%-- Used in tagging to track if user clicked through from search results --%>
				<c:if test="${not empty param.Ntt}">
					<c:choose>
						<c:when test="${fn:indexOf(finalUrl, '?') > -1}">
					 		<dsp:getvalueof id="finalUrl" idtype="String" value="${finalUrl}&fm=search" />
						</c:when>
						<c:otherwise>
					 		<dsp:getvalueof id="finalUrl" idtype="String" value="${finalUrl}?fm=search" />
						</c:otherwise>
					</c:choose>
				</c:if>

				<dsp:a iclass="productcard__a" page="${finalUrl}" role="gridcell">
				  <figure class="productcard__fig">
					 <c:if test="${empty param.Ntt}"> 
						<dsp:param name="categoryId" value="${categoryId}"/>
					 </c:if> 

					<dsp:getvalueof var="prodName" param="element.pageTitle"/>

					<%-- Listing image --%>
					<dsp:include page="inc_grid_productImgLTD.jsp">
						<dsp:param name="product" param="product" />
						<dsp:param name="categoryNav" value="${categoryNav}" />
						<dsp:param name="showAsLink" value="false"/>
						<dsp:param name="defaultImageSize" value="medium"/>
					</dsp:include>

					<figcaption class="productcard__figcap">
						<%-- Price --%>
						<section>
							<p class="productcard__p">					
								<dsp:include page="/catalog/includes/inc_grid_thumbnail_price.jsp" >
									<dsp:param name="product" param="product" />
									<dsp:param name="sku" param="product.childSKUs[0].id" />
								</dsp:include>
							</p>						
						</section>
	
						<%-- description --%>					
						<h2 id="id-prod-COUNTER" class="productcard__h2">${prodName}</h2>
	
						<c:if test="${relProdlabel != 'relProducts'}">
						<%-- Bazaarvoice inline ratings --%>
						<dsp:include page="/bazaarvoice/inc_grid_inLineRating.jsp">
							<dsp:param name="productId" param="product.id"/>
							<dsp:param name="product" param="product"/>
						</dsp:include>
						</c:if>
						
						<c:set var="finalUrl" scope="request"><dsp:valueof value="${finalUrl}" /></c:set>

						<c:if test="${not empty finalUrl}">
							<dsp:droplet name="/atg/dynamo/droplet/Switch">
								<dsp:param name="value" param="product.childSKUs[0].isExclusive" />
								<dsp:oparam name="true">
									<span class="js-productcard-excl">
										<p class="productcard__excl productcard__excl--ltd brand--ltd__show">LTD EXCLUSIVE</p>
										<p class="productcard__excl productcard__excl--lsc brand--lsc__show">LAKESIDE EXCLUSIVE</p>
									</span>
								</dsp:oparam>
							</dsp:droplet>
						</c:if>

							<%-- quick view --%>
						<a class="productcard__a--qv" @click.stop.prevent="toggle" :class="{ hidden: isOpenR__menu }">Quick View</a>
						
					  </figcaption>
					  </figure>
					</dsp:a>
	
					
					<%-- <a class="quick-view button radius" onClick="doaction('<dsp:valueof param="element.repositoryId" />', 'jump', '0','<dsp:valueof param="element.template.url"/>','<c:out value="${requestScope.finalUrl}"/>','','<c:out value="${showSoldOut}"/>')" data-reveal-id="quickViewModal" data-reveal-ajax="true"  data-wsid="ws-quickview">Quick View</a> --%>
				
			
			</dsp:oparam>
		</dsp:droplet>

	</c:if>
</dsp:page>

